### ISSUE TITLE
Update localdev doc

### ISSUE THREAD

**Issue by redrun45** [LibriVox/librivox-ansible#11]
I'm stepping through this process myself on several versions of Ubuntu to see what all needs changed.  See WIP pull request.

**Comment by hamidsafdari** [comment]
@notartom, I've been able to run the app on Ubuntu Server 23.10 inside VirtualBox. I've also imported the database dump. However, on my host machine, when going to either of https://forum.librivox.org, https://wiki.librivox.org, etc., I get a database error saying `librivox_forum.ngo_config` does not exist. I couldn't find it in the repository code. Is it possible the database dump is outdated? Could you maybe paste the DDL for the said table?

**Comment by notartom** [comment]
@hamidsafdari Hello, the database dump is only for the catalog and worklow tool (IOW, https://librivox.org/). This is mostly by design, as there is very little actual development done on our phpBB code (about a dozen custom patches, mostly for cosmetic effect, see https://github.com/LibriVox/librivox-phpBB), and our Wiki installation is entirely vanilla. So the effort-to-value ratio of scrubbing the forum and wiki databases of all personal information and putting them up online is pretty minimal.

**Comment by hamidsafdari** [comment]
That's cool. However, I'm not really sure how to approach setting up my local environment. I really want to help here but I come from a Spring+Angular background and this is quite new to me. Right now, I have the following problems:
1. When I go to https://librivox.org on my host machine, I see a page asking me for a username/password and to install Wordpress. After doing that, I'm taken to an admin page that's pretty much new. I don't see anything under Pages or Users.
2. I do see that Ansible is checking out the code somewhere, but that's not inside the `librivox-ansible` directory. The docs (localdev.md) say the files are in `/librivox`. Looks like it's `/librivox/www/librivox.org/catalog`. So any edits I make should happen there. Is that right?

**Comment by notartom** [comment]
> That's cool. However, I'm not really sure how to approach setting up my local environment. I really want to help here but I come from a Spring+Angular background and this is quite new to me. Right now, I have the following problems:
> 
>     1. When I go to https://librivox.org on my host machine, I see a page asking me for a username/password and to install Wordpress. After doing that, I'm taken to an admin page that's pretty much new. I don't see anything under Pages or Users.

An empty WordPress/blog  installation is expected. librivox.org is actually two Apache sites glued together (see https://github.com/LibriVox/librivox-catalog/blob/master/README.md). On localdev, only the catalog part of it is expected to work, but I agree that the distinction between what pages under librivox.org are blog pages, and which are catalog pages, is not obvious, and should be documented somewhere.

As a quick rule of thumb, anything https://librivox.org/search* is catalog, as well the invidivual audiobook pages (ex: https://librivox.org/library-of-the-worlds-best-literature-ancient-and-modern-volume-17-by-various/), and the autho (https://librivox.org/author*) and reader (https://librivox.org/reader*) pages. https://github.com/LibriVox/librivox-ansible/blob/master/roles/blog%2Bcatalog/templates/librivox.org.conf#L62-L87 is the comprehensive list.

>     2. I do see that Ansible is checking out the code somewhere, but that's not inside the `librivox-ansible` directory. The docs (localdev.md) say the files are in `/librivox`. Looks like it's `/librivox/www/librivox.org/catalog`. So any edits I make should happen there. Is that right?

That's correct, yes.

**Comment by hamidsafdari** [comment]
I've created a pull request, but there are multiple things I probably need to clarify:
1. I've updated the `roles/common/tasks/main.yaml` file to use PHP 7.0. That's what's available on Ubuntu Xenial (16.04). The original PHP 8.2 mentioned in the file is not even available on Ubuntu Bionic (18.04). I know I said I could install the project on Ubuntu Mantic (23.10) but even though I had imported the database and I could browse the `search` page, I saw a lot of PHP errors and there was no data in any of the pages. The PHP errros were mostly about deprecated features that were used by CodeIgniter. Installing LibriVox on Ubuntu Xenial however, worked, and I see everything is OK. I know the production code might be running on PHP 8.2 and that's got me confused on how to make this work. I'm guessing the right approach would be to install PHP 8.2 manually on Ubuntu Xenial and when everything works, try and install the whole thing on Ubuntu 23.10. 
2. No matter what arguments I passed to Ansible, it tried to run everything in the `librivox.yaml` file. I couldn't get it to only run the `localdev` part. That's why I pulled the `localdev` part out of that file and updated the Ansible command. I'll be really happy to learn how the original command worked. Also, it might be worth noting that the installed version of Ansible using the updated doc is 2.5.
3. I've updated the part about shared folders. I've instructed the user to create two shared folders. One for `librivox-ansible` and one for `librivox`. The `librivox` one will be mapped to `/librivox` on the guest machine and Ansible will check out the `librivox-catalog` project inside it. I had originally put the `mount` commands in `/etc/fstab` but the machine wouldn't start since the `pass` argument didn't seem to work. It looked like On Xenial and Bionic, the root partition was not available when mounting the shared folders. Updating `pass` to 0, 1, and 2 didn't seem to fix this.

**Comment by hamidsafdari** [comment]
I have moved everything I could to scripts. The idea is that the user creates a VM, installs git and runs the scripts for everything else. The scripts install Ansible (from source) and its dependencies, runs the Ansible playbook, imports the database dump and make it accessible to the host system.
