### ISSUE TITLE
Target reachable by ssh from OSX shell, but "UNREACHABLE" error when I run ansible playbook

### ISSUE THREAD

**Issue by peterjdann** [LibriVox/librivox-ansible#27]
I am entirely unfamiliar with ansible, but have been following instructions shown here as best I can.

I am running Ubuntu as a virtual machine on an iMac. I am able to ssh as "peterdann" from an OSX session into Ubuntu successfully.

However, when I run the ansible playbook from an OSX session where I am logged in as "peterdann", I get the following message after entering "peterdann" as the BECOME user, followed by the Ubuntu password for "peterdann":

UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: peterdann@10.37.129.3: Permission denied (publickey,password).", "unreachable": true}

**Comment by redrun45** [comment]
I think it might be trying to connect as 'root', instead of first signing in as 'peterdann' and _then_ elevating permissions.
A couple of people [here](https://stackoverflow.com/questions/50855206/unreachable-error-while-running-an-ansible-playbook) have taken different approaches:
* Specify the username by adding `--user=peterdann` (which I think will work with this playbook)
* Add your SSH public key to the root user's authorized keys file (/root/.ssh/authorized_keys in the Ubuntu VM).  I don't know how to set up/ find your SSH public key on MacOS, but you _can_ use the Ubuntu VM as the executor, too.  `ssh-keygen` will make a new keypair, and you can copy the public key from `~/.ssh/id_(your selected key type).pub`.

**Comment by peterjdann** [comment]
Thanks very much for your guidance with this, especially your tip to the effect that I was going about this in a needlessly complicated way.

I appear to have been able to run the playbook successfully locally on a Ubuntu instance, using the one Ubuntu instance as both executor and target.

To do so, I edited inventory.yaml to replace the IP address of the localdev hosts entry with "localhost" (without quote marks).

Then, from the librivox-ansible directory, I executed the following command:
ansible-playbook --connection=local --inventory localhost, --limit localhost  -i inventory.yaml localdev.yaml --ask-become-pass | tee ansible-playbook-installation-log.txt

This appears to have resulted in a successful outcome — though the ultimate proof will yet be in the eating of the pudding.

With kind regards,

Peter Dann
